stages:
  - test
  - build
  - deploy

test:
  tags: [ "runner:docker", "size:large" ]
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/docker:18.03.1
  stage: test
  script:
    - make test

build:binary:
  tags: [ "runner:docker", "size:large" ]
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/docker:18.03.1
  stage: build
  only:
    - tags
  script:
    - make linux
    - ./pkg/bin/linux_amd64/consul version
